site_name: exCSS Documentation
pages:
- Home: index.md
- Functions:
    - Variables: variables.md
    - Grid System: grid.md
    - Animations: animations.md

theme: readthedocs
repo_url: http://github.com/exCSS/core
site_author: Tom Messerschmidt