<?php

	/*
	 * Copyright (C) 2015 Tom Messerschmidt
	 *
	 */


	class Parser
	{
		public function parse($ex_file, $s_file)
			{
				global $VERSION;
				$css = file_get_contents($s_file);
				$ex = parse_ini_file($ex_file, TRUE);
				if(isset($ex['ExtendedCSS']))
				{
					while($cur = current($ex['ExtendedCSS']))
					{
						$var = key($ex['ExtendedCSS']);
						$var_value = $ex['ExtendedCSS'][$var];
						$css = str_replace("$".$var, $var_value, $css);
						next($ex['ExtendedCSS']);
					}
					print "<!-- Generated by exCSS v.". $VERSION ."-->\n";
					print "<style>\n". $css . "\n</style>\n";
					
				}
			}
	}


?>