<?php

	/*
	 * Copyright (C) 2015 Tom Messerschmidt
	 *
	 */

	include 'grid.php';

	class Parser
	{
	
		public function parse($ex_file, $s_file)
			{
				global $VERSION;
				$css = file_get_contents($s_file);
				$ex = parse_ini_file($ex_file, TRUE);
				
				print "<style>";
				print "\n/* Generated by exCSS v.". $VERSION ."*/\n";

				if(isset($ex['ExtendedCSS']))
				{
					while($cur = current($ex['ExtendedCSS']))
					{
						$var = key($ex['ExtendedCSS']);
						$var_value = $ex['ExtendedCSS'][$var];
						$css = str_replace("$".$var, $var_value, $css);
						next($ex['ExtendedCSS']);
					}					
				}
				
			if(isset($ex['Grid']))
			{
				$parts = $ex['Grid']['grid-parts'];		//		how many parts like 1 or 4
				$height = $ex['Grid']['grid-height'];	//		height like 50% or 100%
				$props = $ex['Grid']['grid-props'];		//		proportions like 1-2-1 or 2-3-2
				
				$grid = new Grid($parts, $height, $props);				
			}
			
			foreach( array_keys($ex) as $x )
			{
				if($x == 'Grid' || $x == 'ExtendedCSS')
					continue;
					
				// now there can only be things like .div1 or #div2 or div
				if(isset($ex["Grid"]))
				{
				if(isset($ex[$x]['grid-position']))
				{
						$element_data = $grid->generateCSS($x, $ex[$x]['grid-position']);
						print $element_data;
				}
				}
			}
						print "\n". $css . "\n\n.container{\n\n\tdisplay: table;\n\twidth:100%;\n\theight:100%;\n\n}\n\n</style>\n";

				
			}
	}


?>